import type { PlaylistColumn, PlaylistColumnsState } from "./types";

/**
 * Smallest width in px a resizable column can take. Keeps the resize handle
 * of a narrowed column reachable.
 */
export const MIN_COLUMN_WIDTH = 48;

/**
 * Columns of the Playlist view's table in declaration order, which is also
 * the display order (`docs/specs/v1.3/features/columns.md`). The default
 * visible set mirrors the v1.2 track list: ordinal, title, artist, album,
 * and duration.
 */
export const PLAYLIST_COLUMNS: readonly PlaylistColumn[] = [
  {
    id: "ordinal",
    labelKey: "playlist.column.ordinal",
    width: 44,
    pinned: true,
    defaultVisible: true,
    resizable: false,
    sortable: true,
    align: "end",
  },
  {
    id: "title",
    labelKey: "playlist.column.title",
    width: 280,
    pinned: true,
    defaultVisible: true,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "artist",
    labelKey: "playlist.column.artist",
    width: 200,
    pinned: false,
    defaultVisible: true,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "album",
    labelKey: "playlist.column.album",
    width: 200,
    pinned: false,
    defaultVisible: true,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "albumArtist",
    labelKey: "playlist.column.albumArtist",
    width: 180,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "genre",
    labelKey: "playlist.column.genre",
    width: 140,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "year",
    labelKey: "playlist.column.year",
    width: 72,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "end",
  },
  {
    id: "track",
    labelKey: "playlist.column.track",
    width: 72,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "end",
  },
  {
    id: "disc",
    labelKey: "playlist.column.disc",
    width: 72,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "end",
  },
  {
    id: "composer",
    labelKey: "playlist.column.composer",
    width: 160,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "lyricist",
    labelKey: "playlist.column.lyricist",
    width: 160,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "producer",
    labelKey: "playlist.column.producer",
    width: 160,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "conductor",
    labelKey: "playlist.column.conductor",
    width: 160,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "publisher",
    labelKey: "playlist.column.publisher",
    width: 160,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "bpm",
    labelKey: "playlist.column.bpm",
    width: 72,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "end",
  },
  {
    id: "rating",
    labelKey: "playlist.column.rating",
    width: 104,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "audioFormat",
    labelKey: "playlist.column.audioFormat",
    width: 96,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "addedAt",
    labelKey: "playlist.column.addedAt",
    width: 120,
    pinned: false,
    defaultVisible: false,
    resizable: true,
    sortable: true,
    align: "start",
  },
  {
    id: "duration",
    labelKey: "playlist.column.duration",
    width: 88,
    pinned: false,
    defaultVisible: true,
    resizable: true,
    sortable: true,
    align: "end",
  },
  {
    id: "menu",
    labelKey: null,
    width: 44,
    pinned: true,
    defaultVisible: true,
    resizable: false,
    sortable: false,
    align: "end",
  },
];

/**
 * Column layout before the user changes anything, and what "Reset columns"
 * returns to: the optional columns visible by default and no resized width.
 */
export const DEFAULT_PLAYLIST_COLUMNS_STATE: PlaylistColumnsState = {
  visibleIds: PLAYLIST_COLUMNS.filter(
    (column) => !column.pinned && column.defaultVisible,
  ).map((column) => column.id),
  widths: {},
};
